### ISSUE TITLE
Everything works but model isn't train (problem solved in 1.6 alpha and back with the latest release)

### ISSUE THREAD

**Issue by Hesounolen** [smy20011/dreambooth-gui#57] opened 2022-11-07 22:09 UTC
Hello, 

Just to let you know that I got the same issue that we had before the 1.6 alpha : 
Everything seems to works fine but the model isn't trained when used in stable diffusion. 

I'm using a 3080 ti 12go 
I will stick to the 1.6 for now.
(Didn't tried the 1.7)

Again, thank you for your work !

**Comment by smy20011** [comment] 2022-11-07 22:50
I think you can do a docker pull `smy20011/dreambooth:latest` to fix this problem.

Duplicate of #51

**Closed by smy20011** 2022-11-07 22:50 UTC
